### ISSUE TITLE
spec: Frontmatter's class property targets body as well as html

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/vfm#119]
## Goals

```markdown
---
class: "mypage"
---
```

to

```html
<html class="mypage">
  <body class="mypage">
  </body>
</html>
```

## Prior Art

None

## Discussion

Vivliostyle Slack's `#vfm` channel.

**Comment by akabekobeko** [comment]
Frontmatter 刷新 #76 の際にルートへ定義する `class` は `<html>` のみを対象とし、`<body>` は `body` 内の `class` とすることになった。破壊的な変更であるがアルファ版のバージョン間なのでよしとした。

しかし Slack にて互換を維持したいという要望があり、対応もさほど難しくないので改めて `body` 側へも反映するように検討する。反映のルールについては `class` と `html` の関係を踏襲して以下のようにする予定。

- ルートに `class` が定義されていればそれを `<body class="...">` へ指定
- ルートに `class` が未定義、かつ `body` 内に `class` が定義されていればそれを `<body class="...">` へ指定

つまりはルートを最優先とする。

**Comment by MurakamiShinyu** [comment]
HTMLのclass属性はスペースで区切って複数のクラス名を指定できるものなので、yamlのルート、html、bodyにそれぞれclassの指定があるとき次のようにHTMLに反映されることを期待します：

```yaml
---
class: "mypage"
html:
  class: "myroot"
body:
  class: "mybody"
---
```

to

```html
<html class="mypage myroot">
  <body class="mypage mybody">
  </body>
</html>
```

**Comment by akabekobeko** [comment]
@MurakamiShinyu 

既に実装済みの `html` もそのようになっていません。よって新機能ですね。この案へ対応する場合、ルートの `class` と `html`、`body` のものが同内容だった場合は

```
---
class: "mypage"
html:
  class: "mypage"
body:
  class: "mypage"
---
```

重複を判定しますか？

```html
<html class="mypage">
  <body class="mypage">
  </body>
</html>
```

それともユーザーの自己責任ということで許容しますか？

```html
<html class="mypage mypage">
  <body class="mypage mypage">
  </body>
</html>
```
